server:
  port: 8081

spring:
  application:
    name: User-Management
  cloud:
   config:
    import-check:
     enabled: false

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gradskool
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQLDialect

config:
  import:
    - optional:configserver://localhost:8084
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    show-details: always

resilience4j:
  circuitbreaker:
    instances:
      getSingleStudentCB:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

retry:
  instances:
    getSingleStudentRetry:
      max-attempts: 3
      wait-duration: 500

ratelimiter:
  instances:
    getSingleStudentDenied:
      limit-refresh-period: 4s
      limit-for-period: 2
      timeout-duration: 0s
