server:
  port: 8084

spring:
  application:
    name: config-server
  profiles:
    active: dev

  cloud:
    config:
      server:
        git:
          uri: https://github.com/hrishi177/gradskool-config
          default-label: main


